### ISSUE TITLE
Multi-Homed VM KO, cpi error in mac addresses

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry-attic/bosh_vcloud_cpi#16]
I expected to vcloud CPI to support multi-homed VM.
https://bosh.io/docs/networks.html#multi-homed
https://bosh.io/docs/networks.html#cpi-limitations

My tests where unsuccessfull. Bosh Director gives 2 IP adress (ok on bosh vms), but the stemcell fails to configure the second NIC.

Having a look at the file /var/vcap/job/settings.json, I see that the 2 nics are set on the same MAC (whereas i have 2 distincts generated MACs, confirmed in vcloud portal).

For me its a blocker. I would be glad if you had any workaround.

**Comment by poblin-orange** [comment]
I did previously open an issue on this point (maybe in a wrong location)
https://github.com/cloudfoundry-attic/bosh_vcloud_cpi/issues/16

Had no time to reproduce the issue, but its looking very similar (vcloud cpi, multi homed nics)

**Comment by cppforlife** [comment]
Moved issue to bosh-vcloud-cpi-release.
